#!/usr/bin/env python3
"""Build web/data.js (script + timeline) from script/script.json.

If build/tts/<n>.wav exists for every sentence, real narration durations are used;
otherwise durations are estimated from the text so the video can be previewed
before TTS is available.
"""
import json, os, re, wave, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT = os.path.join(ROOT, "script", "script.json")
TTS_DIR = os.path.join(ROOT, "build", "tts")
OUT = os.path.join(ROOT, "web", "data.js")

FPS = 30
LEAD = 1.5        # chapter title card before the first sentence
FIRST_LEAD = 4.5  # main title + first chapter card
GAP = 0.36        # pause between sentences (subtitles switch inside it)
TAIL = 0.8        # breathing room at the end of a chapter
OUTRO = 2.5       # extra hold on the final frame


def estimate(text):
    cjk = len(re.findall(r"[一-鿿]", text))
    words = len(re.findall(r"[A-Za-z]+|\d+(?:\.\d+)?", text))
    pauses = len(re.findall(r"[，、；：,;:]", text))
    return cjk * 0.21 + words * 0.30 + pauses * 0.15 + 0.2


def wav_len(path):
    with wave.open(path) as w:
        return w.getnframes() / w.getframerate()


def main():
    script = json.load(open(SCRIPT, encoding="utf-8"))
    flat = [(ci, si, s) for ci, ch in enumerate(script["chapters"]) for si, s in enumerate(ch["sentences"])]
    wavs = [os.path.join(TTS_DIR, f"{n:03d}.wav") for n in range(len(flat))]
    have_tts = all(os.path.exists(p) for p in wavs)

    t = 0.0
    chapters, sentences = [], []
    for ci, ch in enumerate(script["chapters"]):
        start = t
        lead = FIRST_LEAD if ci == 0 else LEAD
        t += lead
        for si, s in enumerate(ch["sentences"]):
            n = len(sentences)
            dur = wav_len(wavs[n]) if have_tts else estimate(s.get("tts", s["zh"]))
            sentences.append({"n": n, "c": ci, "k": si, "start": round(t, 3), "end": round(t + dur, 3),
                              "zh": s["zh"], "en": s["en"]})
            t += dur + GAP
        t += TAIL - GAP
        if ci == len(script["chapters"]) - 1:
            t += OUTRO
        chapters.append({"id": ch["id"], "zh": ch["zh"], "en": ch["en"], "start": round(start, 3), "lead": lead,
                         "end": round(t, 3)})

    timeline = {"fps": FPS, "duration": round(t, 3), "narrated": have_tts,
                "chapters": chapters, "sentences": sentences}
    data = {"title": script["title"], "voice": script["voice"], "characters": script["characters"],
            "timeline": timeline}
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/timeline.py — do not edit by hand.\n")
        f.write("window.CASCCS_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write(";\n")
    print(f"{'TTS' if have_tts else 'ESTIMATED'} timeline: {len(chapters)} chapters, "
          f"{len(sentences)} sentences, {t:.1f}s")
    for c in chapters:
        print(f"  {c['start']:7.1f} → {c['end']:7.1f}  ({c['end']-c['start']:5.1f}s)  {c['zh']}")


if __name__ == "__main__":
    main()
